[server]
fileWatcherType = "poll"
layout = "wide"                    # Diseño amplio para aprovechar espacio
initial_sidebar_state = "expanded"  # Barra lateral abierta por defecto

[theme]
primaryColor = '#6B46C1'           # Violeta elegante como base
backgroundColor = '#F8F6FF'        # Fondo con un tono violeta claro
secondaryBackgroundColor = '#EEEAF5'  # Gris lavanda para contrastar
textColor = '#1A202C'              # Texto en gris oscuro para buena legibilidad
font = 'monospace'                 # Fuente principal para todo el contenido

[title_style]
fontSize = "1.7rem"                # Tamaño ajustado para títulos
fontWeight = "700"                 # Negrita para resaltar
color = "#6B46C1"                  # Violeta principal para cohesión visual

[subheader_style]
fontSize = "1.3rem"                # Tamaño reducido para subtítulos
fontWeight = "600"                 # Semi-negrita para diferenciación
color = "#805AD5"                  # Violeta más suave

[text_style]
fontSize = "1rem"                  # Tamaño estándar para explicaciones
fontWeight = "400"                 # Peso normal para legibilidad
color = "#4A5568"                  # Gris intermedio

[input_style]
font = 'sans serif'                # Fuente moderna para inputs y campos editables
fontSize = "0.9rem"                # Tamaño compacto para inputs
fontWeight = "500"                 # Peso moderado para claridad
color = "#333333"                  # Gris oscuro para inputs
backgroundColor = "#E2DFFA"        # Fondo violeta claro para inputs y botones
borderColor = "#6B46C1"            # Bordes violeta para inputs
