[server]
fileWatcherType = "poll"

[theme]
primaryColor = '#6B46C1'          # Violeta elegante
backgroundColor = '#FFFFFF'       # Fondo blanco limpio
secondaryBackgroundColor = '#F9FAFB'  # Gris suave
textColor = '#1A202C'             # Casi negro para texto
font = 'monospace'                # Fuente monoespaciada
